// react-app/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import "@library/styles/core.css";
import {
  WithContext,
  WithContextContent,
} from "@library/components/with-context";
import { SimpleTest } from "@library/components/simple-test";
function App() {
  const [count, setCount] = useState(0);

  return (
    <WithContext>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <WithContextContent />
      <SimpleTest />
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </WithContext>
  );
}

export default App;

// vue-project/src/App.vue
<script setup lang="ts">
import "../../library/dist/styles/core.css";
import HelloWorld from "./components/HelloWorld.vue";
import {
  SimpleTest,
  WithContext,
  WithContextContent,
} from "../../library/dist/components/vue";
</script>

<template>
  <WithContext>
    <div>
      <a href="https://vite.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <HelloWorld msg="Vite + Vue" />
    <SimpleTest />
    <WithContextContent />
  </WithContext>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
